user: 'myusername@tenant_name'
password: 'xxxxxxxxxxxx'
wsdl_url: 'https://server_name/ccx/service/tenant_name/Human_Resources/v40.1?wsdl'
binding_path: '{urn:com.workday/bsvc/Human_Resources}Human_ResourcesBinding'
