# for example bking@amu - though this won't actually work on a shared demo tenant
# unless you have the user's password
user: 'myusername@tenant_name'
password: 'xxxxxxxxxxxx'
# for example https://sharedamupreview.workdaysuv.com/ccx/service/amu/Student_Records/v40.1?wsdl
wsdl_url: 'https://server_name/ccx/service/tenant_name/Student_Records/v40.1?wsdl'
binding_path: '{urn:com.workday/bsvc/Student_Records}Student_RecordsBinding'
